MyPOS/Models/Customer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace MyPOS.Models
{
    public class Customer
    {
        [Key]
        public int CustomerID { get; set; }

        [Required]
        [Display(Name = "Name")]
        [StringLength(12, ErrorMessage = "Please shorten the Customer Name to 12 characters")]
        public string CustomerName { get; set; }

        [Required]
        [StringLength(50)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Your must provide a Phone Number")]
        [Display(Name = "Phone Number")]
        [StringLength(12, ErrorMessage = "Please vali Phone Number")]
        public string Phone { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

        public ICollection<OrderMenu> OrderMenu { get; set; }
    }
}

MyPOS/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPOS.Data;
using MyPOS.Models;
using MyPOS.Models.CustomerViewModels;

namespace MyPOS.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customer.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CustomerDetailViewModel model = new CustomerDetailViewModel(_context);

            model.Customer = await _context.Customer
                .Include(m => m.Orders)
                .Include(m => m.OrderMenu)
                .ThenInclude(m => m.MenuItem)
                .ThenInclude(m => m.MenuCategory)
                .SingleOrDefaultAsync(m => m.CustomerID == id);

            model.GroupedItems = await (
                from t in _context.MenuCategory
                join p in _context.MenuItem
                on t.MenuCategoryID equals p.MenuCategoryID
                group new { t, p } by new { t.MenuCategoryID, t.MCTitle } into grouped
                select new GroupedItems
                {
                    CategoryID = grouped.Key.MenuCategoryID,
                    TypeName = grouped.Key.MCTitle,
                    MenuItem = grouped.Select(x => x.p)
                }).ToListAsync();

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerID,CustomerName,Address,Phone")] Customer customer, int id)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = customer.CustomerID });
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.SingleOrDefaultAsync(m => m.CustomerID == id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerID,CustomerName,Address,Phone")] Customer customer)
        {
            if (id != customer.CustomerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .SingleOrDefaultAsync(m => m.CustomerID == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.SingleOrDefaultAsync(m => m.CustomerID == id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.CustomerID == id);
        }
    }
}

MyPOS/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPOS.Data;
using MyPOS.Models;
using MyPOS.Models.OrderViewModels;

namespace MyPOS.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.Customer).Include(o => o.PaymentType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Customer)
                .Include(o => o.PaymentType)
                .SingleOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["CustomerID"] = new SelectList(_context.Set<Customer>(), "CustomerID", "Address");
            ViewData["PaymentTypeID"] = new SelectList(_context.Set<PaymentType>(), "PaymentTypeID", "Type");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,PaymentTypeID,CustomerID")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CustomerID"] = new SelectList(_context.Set<Customer>(), "CustomerID", "Address", order.CustomerID);
            ViewData["PaymentTypeID"] = new SelectList(_context.Set<PaymentType>(), "PaymentTypeID", "Type", order.PaymentTypeID);
            return View(order);
        }

        public async Task<Order> CreateOrder(int id)
        {
            Order order = new Order();
            order.CustomerID = id;
            _context.Add(order);
            await _context.SaveChangesAsync();
            return order;
        }

        public async Task<IActionResult> AddProduct(int id, int custID)
        {
            CreateOrderViewModel model = new CreateOrderViewModel();

            model.Orders = await _context.Order.SingleOrDefaultAsync(m => m.PaymentTypeID == null);

            if (model.Orders == null)
            {
                model.Orders = await CreateOrder(custID);
            }

            OrderMenu orderMenu = new OrderMenu();
            orderMenu.CustomerID = custID;
            orderMenu.Orders = model.Orders;
            orderMenu.MenuItem = await _context.MenuItem.SingleOrDefaultAsync(p => p.MenuItemID == id);
            _context.Add(orderMenu);

            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Customers", new { id = orderMenu.CustomerID });
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.SingleOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CustomerID"] = new SelectList(_context.Set<Customer>(), "CustomerID", "Address", order.CustomerID);
            ViewData["PaymentTypeID"] = new SelectList(_context.Set<PaymentType>(), "PaymentTypeID", "Type", order.PaymentTypeID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,PaymentTypeID,CustomerID")] Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Create", "Customers");
            }
            ViewData["CustomerID"] = new SelectList(_context.Set<Customer>(), "CustomerID", "Address", order.CustomerID);
            ViewData["PaymentTypeID"] = new SelectList(_context.Set<PaymentType>(), "PaymentTypeID", "Type", order.PaymentTypeID);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.Customer)
                .Include(o => o.PaymentType)
                .SingleOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Order.SingleOrDefaultAsync(m => m.OrderID == id);
            _context.Order.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteProduct(int id)
        {

            var orderMenu = await _context.OrderMenu.SingleOrDefaultAsync(p => p.OrderMenuID == id);
            _context.OrderMenu.Remove(orderMenu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Customers", new { id = orderMenu.CustomerID });
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.OrderID == id);
        }
    }
}

MyPOS/Views/Customers/Create.cshtml
@model MyPOS.Models.Customer

@{
    ViewData["Title"] = "Get Customer";
}

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Customer Info</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CustomerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyPOS/Views/Customers/Delete.cshtml
@model MyPOS.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="CustomerID" />
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

MyPOS/Views/Customers/Details.cshtml
@model MyPOS.Models.CustomerViewModels.CustomerDetailViewModel

@{
    ViewData["Title"] = "Details";
    var group = Model.Customer.OrderMenu.GroupBy(i => i.MenuItemID);
    var groupCategory = Model.MenuItem.GroupBy(i => i.MenuCategoryID);
}

<h2>Complete Order</h2>
<div class="flex">
    <div class="item invoice">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Customer.CustomerName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Customer.CustomerName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Customer.Address)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Customer.Address)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Customer.Phone)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Customer.Phone)
            </dd>
        </dl>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        <h5>Products</h5>
                    </th>
                    <th>
                        <h5>Quantity</h5>
                    </th>
                    <th>
                        <h5>Price</h5>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in group)
                {
                    foreach (var i in item)
                    {
                        <tr>
                            <td>
                                <h5>@i.MenuItem.MITitle</h5>
                            </td>
                            <td>
                                <h5>@i.MenuItem.OrderMenu.Count(m => m.OrderID == i.OrderID)</h5>
                            </td>
                            <td>
                                <h5>@i.MenuItem.Price</h5>
                            </td>
                            @if (@i.Orders.PaymentTypeID == null)
                            {
                                <td>
                                    <form asp-controller="Orders" asp-action="DeleteProduct" asp-route-id="@i.OrderMenuID">
                                        <div class="form-group">
                                            <input type="submit" value="Delete" class="btn btn-danger" />
                                        </div>
                                    </form>
                                </td>
                            }
                        </tr>
                        break;
                    }
                }
            </tbody>
            <tfoot>

                <tr>
                    <th>
                        Subtotal: @Model.OrderMenu.Where(m => m.OrderID == m.Orders.OrderID && m.Orders.PaymentTypeID == null).Sum(o => o.MenuItem.Price * 0.0925 + (o.MenuItem.Price)).ToString("0.00")
                    </th>
                </tr>

                <tr>
                    <th>
                        Tax: @Model.OrderMenu.Where(m => m.OrderID == m.Orders.OrderID && m.Orders.PaymentTypeID == null).Sum(o => o.MenuItem.Price * 0.0925).ToString("0.00")
                    </th>
                </tr>

            </tfoot>
        </table>
        @foreach (var item in Model.Order)
        {
            if (item.PaymentTypeID == null)
            {
            <div>
                <a class="btn btn-success menu-button" asp-controller="Orders" asp-action="Edit" asp-route-id="@item.OrderID">Purchase</a>
            </div>
                break;
            }
        }
    </div>

    <div class="item menu">
        @foreach (var item in Model.GroupedItems)
        {
            <table>
                <tbody>
                    <tr>
                        <th class="btn btn-info menu-button">@item.TypeName</th>
                        @foreach (var j in item.MenuItem)
                        {
                        <td>
                            <form asp-controller="Orders" asp-action="AddProduct" asp-route-id="@j.MenuItemID" asp-route-custID="@Model.Customer.CustomerID">
                                <input type="submit" value="@j.MITitle" class="btn btn-primary menu-button " />
                            </form>
                        </td>
                        }
                    </tr>
                </tbody>
            </table>
        }
    </div>
</div>
<hr />
<div class="col-lg-push-12">
    <a asp-action="Edit" asp-route-id="@Model.Customer.CustomerID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyPOS/Views/Customers/Edit.cshtml
@model MyPOS.Models.Customer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CustomerID" />
        <div class="form-group">
            <label asp-for="CustomerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyPOS/Views/Customers/Index.cshtml
@model IEnumerable<MyPOS.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CustomerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Phone)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CustomerID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CustomerID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>